# NumPy

---
## Introducción

NumPy es un módulo de Python. El nombre viene de **PY**thon **NUM**érico. Es una librería de código abierto muy utilizada para la generación y manejo de matrices multidimensionales. En su mayor parte está escrito en C para optimizar su velocidad de ejecución.

Además, los objetos de Pandas (librería que veremos próximamente) dependen en gran medida de los objetos de NumPy ya que Pandas extiende a NumPy.

Aquí os dejo la url de la [documentación oficial](https://numpy.org/doc/stable/) de NumPy.

In [1]:
import numpy as np # np es el diminutivo por defecto que se suele ver en internet

---
## Arrays

Con NumPy podemos crear arrays de todo tipo de dimensiones: 1D, 2D, 3D...
Para ello, podremos utilizar los siguientes comandos:

In [2]:
# NumPy cuenta con la función "array" que crea su propia estructura de datos de array en función de los datos recibidos
# 1D
a = np.array([1,2,3])
print(a)

# 2D con listas de listas
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

# 2D con listas de tuplas
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


---
## Tipos de datos

Con NumPy puedes decidir el tipo de datos de un array. Hecho muy importante ya que en función de esto dependerá la información que almacenemos y el espacio que ocupe en memoria:

In [7]:
array_float = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float64) # hay distintos tipos de float: 16, 32, 64
print(array_float)
print(type(array_float[0][0]))

# Al igual que float, también hay distintos tipos de int (8, 16, 32, 64),
array_int = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int8)
print(array_int)
print(type(array_int[0][0]))

# Habrá que tener cuidado ya que cada tipo de dato tiene su límite numérico
array_int = np.array([[1,2,3,4],[5,6,7,1000]], dtype=np.int8)
print(array_int)

[[1.       2.       3.       4.      ]
 [5.       6.       7.       8.777777]]
<class 'numpy.float64'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.int8'>
[[  1   2   3   4]
 [  5   6   7 -24]]


---
## Matrices predefinidas

Otra de las ventajas es que NumPy permite crear matrices vacías o rellenas con valores aleatorios de distintas formas

In [11]:
# matriz rellena de unos
unos = np.ones((3,4))
print(unos)

# matriz rellena de ceros
ceros = np.zeros((2,5))
print(ceros)

# matriz rellena de números aleatorios (entre 0 y 1)
aleatorios = np.random.random((3,3))
print(aleatorios)

# matriz vacía
vacia = np.empty((2,2))
print(vacia)

# matriz con un mismo valor
valor = np.full((2,3), 5)
print(valor)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.91371176 0.12089828 0.93585652]
 [0.04108492 0.0562216  0.31157148]
 [0.04978817 0.28589503 0.80154902]]
[[1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]]


Si en lugar de crear valores de las formas anteriores preferimos crearlos en un intérvalo concreto podremos utilizar estas dos funciones:

In [9]:
# crea una matriz con valores especificados en función de un rango
m1 = np.arange(0, 50, 5)
print(m1)

# crea matriz con valores entre dos datos y definiendo el número de elementos
m2 = np.linspace(0, 10, 5)
print(m2)

[ 0  5 10 15 20 25 30 35 40 45]
[ 0.   2.5  5.   7.5 10. ]


Por último, una matriz muy típica es la matriz "identidad". Si queremos generar este tipo de matrices tenemos dos formas:

In [10]:
# genera matrices de identidad de cualquier dimensión
id1 = np.eye(4,4)
print(id1)

# genera matrices de identidad cuadradas
id2 = np.identity(4)
print(id2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
## Funciones sobre matrices

NumPy incluye una serie de funciones útiles a la hora de inspeccionar las matrices generadas:

In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[[1.1,2.2,3.3],[4.4,5.5,6.6]],[[7.7,8.8,9.9],[10.1,11.2,12.3]]])

print(a)
print(b)
# saber las dimensiones de un array
print("Dimensiones A: ", a.ndim)
print("Dimensiones B: ", b.ndim)

# conocer el tipo de datos de un array
print("Tipo A: ", a.dtype)
print("Tipo B: ", b.dtype)

# para conocer el tamaño y la forma de una matriz
print("Tamaño A: ", a.size)
print("Forma A: ", a.shape)
print("Tamaño B: ", b.size)
print("Forma B: ", b.shape)


[[1 2 3]
 [4 5 6]]
[[[ 1.1  2.2  3.3]
  [ 4.4  5.5  6.6]]

 [[ 7.7  8.8  9.9]
  [10.1 11.2 12.3]]]
Dimensiones A:  2
Dimensiones B:  3
Tipo A:  int32
Tipo B:  float64
Tamaño A:  6
Forma A:  (2, 3)
Tamaño B:  12
Forma B:  (2, 2, 3)


También podemos cambiar el tamaño y la forma de las matrices:

In [ ]:
# aprovechamos el elemento "a" creado en el bloque anterior
print("a: ", a)

# modificamos su forma para que en lugar de 2 filas y 3 columnas sea 3 filas y 2 columnas:
c = a.reshape(3,2) # Esto no ha almacenado el cambio sobre "a" sino sobre "c"
print("c: ", c)

a:  [[1 2 3]
 [4 5 6]]
c:  [[1 2]
 [3 4]
 [5 6]]


---
## Trabajo sobre posiciones de una matriz

NumPy también ofrece unas maneras más sencillas para trabajar sobre posiciones concretas de una matriz:

In [ ]:
matriz = np.random.random((2,5))
print(matriz)

# si quiero obtener el elemento de una posición concreta
print(matriz[0,2])

# si quiero obtener todas las filas de una columna concreta
print(matriz[:,4])

# si quiero obtener una submatriz de la matriz
print(matriz[:,0:2])

[[0.5321589  0.69771584 0.98954261 0.24354292 0.97875716]
 [0.38848457 0.49000974 0.62469785 0.90849755 0.69364604]]
0.9895426137153429
[0.97875716 0.69364604]
[[0.5321589  0.69771584]
 [0.38848457 0.49000974]]


---
## Modificación de arrays

Si quisieramos modificar matrices creadas anteriormente podríamos tanto insertar como eliminar partes de las mismas:

In [ ]:
matriz = np.random.randint(10, size=(1,5))
print(matriz)

# Añadimos tres nuevos elementos
matriz = np.append(matriz, [10, 10, 10])
print(matriz)

# Eliminamos el último elemento
matriz = np.delete(matriz, 7)
print(matriz)

# Eliminamos los dos últimos elementos
matriz = np.delete(matriz, [5,6])
print(matriz)

[[1 2 8 0 7]]
[ 1  2  8  0  7 10 10 10]
[ 1  2  8  0  7 10 10]
[1 2 8 0 7]
